### ISSUE TITLE
Reading file in causes 'index out of bounds' error

### ISSUE THREAD

**Issue by marcus0596** [DnOberon/tdms#1]
I am attempting to read in a tdms file so I can perform calculations on the data contained within. The structure of the file is this:

```
test.tdms
    aux_data
        time [s] 
        distance [in]
        gps 
    mic_data
        time [s]
        mic 1
        mic 2 
        ... mic 12
```

Reading in this test.tdms file like so:

```
let file = match TDMSFile::from_path(Path::new("src/data/test.tdms")) {
        Ok(f) => f,
        Err(e) => panic!("{:?}", e),
    };
```

throws the following error. I fear that the error is due to the tiered structure of my data because reading in the provided (non-tiered) standard, raw, and big endian tdms files works fine. 

```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', C:\...\.cargo\registry\src\github.com-1ecc6299db9ec823\tdms-0.2.5\src\segment.rs:114:75
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
   2: core::panicking::panic_bounds_check
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:84
   3: core::slice::index::impl$2::index<str>
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\slice\index.rs:250
   4: core::slice::index::impl$0::index
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\slice\index.rs:18
   5: alloc::vec::impl$16::index<str,usize,alloc::alloc::Global>
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\alloc\src\vec\mod.rs:2628
   6: tdms::segment::Segment::new<std::io::buffered::bufreader::BufReader<std::fs::File> >
             at C:\...\.cargo\registry\src\github.com-1ecc6299db9ec823\tdms-0.2.5\src\segment.rs:114
   7: tdms::TDMSFile::from_path
             at C:\...\.cargo\registry\src\github.com-1ecc6299db9ec823\tdms-0.2.5\src\lib.rs:124
   8: test::tdms_reader::open
             at .\src\tdms_reader.rs:11
   9: test::main
             at .\src\main.rs:15
  10: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\ops\function.rs:248
```

**Comment by DnOberon** [comment]
Hi there! I haven't had a chance to work on this library for a while, so apologies in advance for that.  Are you willing to share your test file with me so I can see what's going on?

**Comment by marcus0596** [comment]
Absolutely, thank you for the fast response. Here's a link to my test file that fails to read in: [tdmsHandler](https://github.com/marcus0596/tdmsHandler/).

**Comment by DnOberon** [comment]
I finally had a chance to take a look at this @marcus0596. I'm sorry for the super delayed response and you probably already moved to another TDMS reader, but I was unable to recreate the error with the TDMS file in that directory you linked.

I was able to inspect and dive into the file just fine - but maybe you've changed it since the last time I looked?

**Comment by DnOberon** [comment]
I believe I've corrected your error @marcus0596 . Apologies for taking so long, the joys of open source side projects. Hopefully you've been able to make progress, or moved to a different parser in the meantime!
