### ISSUE TITLE
TDMSValue from_path method do not exist

### ISSUE THREAD

**Issue by Mat-moran** [DnOberon/tdms#2]
Hi,

I am starting with rust and labview and I am trying out this library, thanks for the work men!

Just a question about how to extract a value from a `TDMSValue`. In this particular case I need to extract the date to send it to a `.csv` file. I have this function:

```rust
fn extract_date(tdms_file: &TDMSFile, file: &mut File) -> std::io::Result<()> {
    let name = tdms_file.segments.get(0).unwrap().metadata.clone().unwrap();
    let obj = name
        .objects
        .iter()
        .find(|obj| obj.object_path == "/")
        .unwrap();
    // .collect();
    let date = obj
        .properties
        .iter()
        .find(|n| n.name == "DateTime")
        .unwrap()
        .value
        .clone();
    println!("extract date ---------->>> {:?}", date);
    Ok(())
}
```

`date` is of type `TDMSValue`, reading the docs I found that this struct has a method [pub fn from_reader(...)](https://docs.rs/tdms/0.3.0/src/tdms/data_type.rs.html#105-347) 
that I supose that is to extract that value from value depending on each type, but It seems that this function does not exists. I am not able to call this function.

![image](https://user-images.githubusercontent.com/4810013/228320037-c0a3b26e-54ec-4bc4-8b2a-6557ed7f50d0.png)

Do you know what can be happening? any help is welcome. 😃

**Comment by DnOberon** [comment]
Sorry I missed this. 

I think it's a misunderstanding what what I made public. `from_reader` is supposed to take the underlying `Read + Seek` from when I open the TDMS file and read the correct amount of bytes that represent that TDMS data type, and return that data type.  In the metadata there are a few fields who's type are the TDMS DateTime - but if you're looking at pulling a channel's data who's value type is that TDMS Timestamp, then you'll need to get the iterator for that channel like we do here https://github.com/DnOberon/tdms/blob/main/examples/segments.rs#L24. 

Hopefully that helps? TDMS is confusing enough and I'm sorry if I made it worse
